---
title: Cover_letter
format:
  quarto-cv-pdf: default
author: Katinka Lennemann
date: last-modified
phone: +1 (650)-284-6140
# address: "Guinness Brewery · Park Royal · London NW10 7RR, UK"
email: klennemann@ucla.edu
fontsize: 11pt
# fontfamily: ebgaramond-maths # default font LaTeX package https://tug.org/FontCatalogue/about.html
#mainfont: Ubuntu # if you want to use a different locally installed font
#CJKmainfont: Noto Sans CJK JP # locally installed Asian character font, must use with xelatex
# github: klennemann # github account
# linkedin: in/katinka-lennemann # this doesn't work
# orcid: 0000-0002-1825-0097 # orcid identifier
#osf: ymqui # osf five character id
#twitter: twitter # twitter handle
# web: quarto.org
fontawesome: yes
nocite: '@*'
# bibliography: 
#  peer: peer_bib.bib
#  other: other_bib.bib
validate-yaml: false
csl: apa-cv.csl
geometry:
  - top=16mm
  - left=16mm
  - right=16mm
  - bottom=16mm
---

\vspace{30pt}

Institute for Higher Education Policy\
1615 L Street, NW,\
Suite 310 Washington, DC 20036

\vspace{30pt}

Dear Hiring Manager,

\vspace{15pt}

My name is Katinka Lennemann; I'm writing to express my interested in the 2026 Spring Research Intern position at the Institute for Higher Education Policy!

I"m passionate about using creative research and policy design skills for social impact. Through my role as a curriculum coordinator, I conducted qualitative research with frontline communities being affected by the issue of land subsidence in the Central Valley, focusing the equity aspect of how those most affected should be centered in the solution-making as well. I also have experience doing policy research and literature review in my role as the U.S. Delegate to the ASEAN Foundation's Model East Asia Summit, where I did surveyed the existing environment of offshore renewable energy development and roadblocks the industry faces. These experiences taught me to be creative when looking for data, and moreover, how to communicate those finndings clearly to others.

This role aligns not only with my rigorous research and communication skills, but also where I want to end up in the future: I believe that policy is truly the foundation of making instrumental change. What's more, it's in higher education that I discovered the power of policy. In this complex society, I believe that we need to make sure post-secondary education is affordable and accessible for all. My own dad, an immigrant to America, found footing to grow a family here because he was able to use his degree to secure a job, to find stability.

In these difficult political times, it is even more important that educational rights are not eroded. Whether that be through IHEP's focus areas of data & transparency, promoting educational completion, or equity in the admissions process, I would truly appreciate the opportunity to contribute to IHEP's mission.

Thank you for considering my application.

\vspace{15pt}

Best,\
Katinka Lennemann
