---
title: Resume
format:
  quarto-cv-pdf:
    include-in-header:
      text: |
        \usepackage{parskip}
        \setlength{\parskip}{0pt}
        \setlength{\itemsep}{-5pt}
        \setlength{\topsep}{-5pt}
author: Katinka Lennemann
date: last-modified
phone: +1 (650)-284-6140
# address: "Guinness Brewery · Park Royal · London NW10 7RR, UK"
email: klennemann@ucla.edu
fontsize: 11pt
# fontfamily: ebgaramond-maths # default font LaTeX package https://tug.org/FontCatalogue/about.html
#mainfont: Ubuntu # if you want to use a different locally installed font
#CJKmainfont: Noto Sans CJK JP # locally installed Asian character font, must use with xelatex
# github: klennemann # github account
linkedin: in/katinka-lennemann # this doesn't work
# orcid: 0000-0002-1825-0097 # orcid identifier
#osf: ymqui # osf five character id
#twitter: twitter # twitter handle
# web: quarto.org
fontawesome: yes
nocite: '@*'
# bibliography: 
#  peer: peer_bib.bib
#  other: other_bib.bib
validate-yaml: false
csl: apa-cv.csl
geometry:
  - top=16mm
  - left=16mm
  - right=16mm
  - bottom=16mm
---


# PROFESSIONAL EXPERIENCE

**San Mateo County Sustainability Department**\
*Climate Protection Team Intern* \hfill Jun. 2025 - Aug. 2025

-   Built spatial map in ArcGIS to identify high impact sites for EV chargers by integrating electric grid load capacity, charger density, and demographic data
-   Used Excel to created dashboard of performance metrics for 15 clean energy incentive programs, identifying trends to inform future program design and funding allocation
-   Supported data-driven evaluation of school decarbonization by inventorying over 100 methane-fueled appliances across 12+ school sites to estimate greenhouse gas savings

**Global Nomads Group**\
*Curriculum Coordinator* \hfill Jun. 2023 - Dec. 2024

-   Coordinated development of a climate change curriculum on water management and land subsidence, informed by data and policy research and field-tested in 100+ California schools
-   Synthesized research from academic literature and interviews with USGS geologists, tribal governments, water managers, and frontline communities into clear, evidence-based materials for a general audience
-   Reviewed outputs for accuracy and consistency, incorporating field-test feedback to refine content and maintain alignment with program objectives


**Each Green Corner**\
*Data Evaluation Intern* \hfill Feb. 2023 - Jun. 2023

-   Transformed disconnected raw data to a live summary metrics and visualizations page
-   Conducted analysis on site performance trends and wrote actionable reports on how to improve operations

--- 

# EDUCATION

**University of California, Los Angeles**\
*B.S. Applied Mathematics, B.S. Statistics & Data Science - GPA: 3.8*

-   Relevant coursework: Statistical Models and Data Mining, Computation and Optimization in R, Foundations of Environmental Policy and Regulation, Applied Numerical Methods
-   Academies of Social Entrepreneurship Alumni: conducted market research and analyzed large public school datasets to pitch a new business venture for California Youth Services (CYS), an mental health nonprofit

--- 

# VOLUNTEERING

**California Youth Services**\
*Data Management & Processing* \hfill Jul. 2025 - Present

-   Developing back-end forms and workflow reports in Apricot Social Solutions to streamline data entry and reporting

**California Youth Climate Policy Leadership Program**\
*Mentor* \hfill Aug. 2022 - Present (seasonal)

-   Providing mentorship and guidance to California high schoolers on carrying out climate policy campaigns

---

# SKILLS AND TOOLS

**Technical:** R, Excel, Python, SQL, Power BI, Google Workspace, Microsoft Office, ChatGPT \
**Languages:** English (native), Mandarin (fluent)